{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "nginx-ingress.name" . }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nginx-ingress-operator-nginx-ingress-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
