apiVersion: charts.nginx.org/v1alpha1
kind: NginxIngress
metadata:
  name: nginxingress-sample
spec:
  # Default values copied from <project_dir>/helm-charts/nginx-ingress/values.yaml
  controller:
    defaultTLS:
      secret: nginx-ingress/default-server-secret
    enableCustomResources: true
    image:
      pullPolicy: IfNotPresent
      repository: nginx/nginx-ingress
      tag: 2.1.0-ubi
    ingressClass: nginx
    kind: deployment
    nginxplus: true
    service:
      type: NodePort
  rbac:
    create: true
