# permissions for end users to view nginxingresscontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxingresscontroller-viewer-role
rules:
- apiGroups:
  - k8s.nginx.org
  resources:
  - nginxingresscontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.nginx.org
  resources:
  - nginxingresscontrollers/status
  verbs:
  - get
