# permissions for end users to view nginxingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxingress-viewer-role
rules:
- apiGroups:
  - charts.nginx.org
  resources:
  - nginxingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.nginx.org
  resources:
  - nginxingresses/status
  verbs:
  - get
