# permissions for end users to edit nginxingresscontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxingresscontroller-editor-role
rules:
- apiGroups:
  - k8s.nginx.org
  resources:
  - nginxingresscontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.nginx.org
  resources:
  - nginxingresscontrollers/status
  verbs:
  - get
