apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: my-nginx-ingress-controller
spec:
  type: deployment
  nginxPlus: false
  image:
    repository: docker.io/nginx/nginx-ingress
    tag: 2.1.1-ubi
    pullPolicy: Always
  serviceType: NodePort
  ingressClass: nginx
