name: Lint

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '**.md'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-lint
  cancel-in-progress: true

env:
  GOLANGCI_TIMEOUT: 10m0s

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Lint Code
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout ${{ env.GOLANGCI_TIMEOUT }}
